# 配置hr包下的日志输出级别
logging:
  level:
    com:
      handge:
        hr:
          debug

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mybatistest?useUnicode=true&characterEncoding=utf8
    url: jdbc:postgresql://172.20.31.108:5432/hr
    username: postgres
    password: postgres
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver
  data:
     elasticsearch:
       cluster-name: handge-cloud
       cluster-nodes: 172.20.31.4:9300,172.20.31.5:9300,172.20.31.6:9300
  jpa:
      properties:
        hibernate:
           temp:
              use_jdbc_metadata_defaults: false

mybatis:
  configuration:
      cache-enabled: true
      map-underscore-to-camel-case: true
      lazy-loading-enabled: true
      aggressive-lazy-loading: false

server:
  redis:
    shiro:
      port: 6380
      host: 172.20.31.4
      expire: 1800
      sessionInMemoryTimeout: 60000
      key: username

custom:
  login:
    role:
      is-validate: false
    hyper-role:
      ip-validate: false
      allows:
